#!/bin/bash

bm="$(dirname "$0")";
data="$bm/internal/static/";
jslibHTML="$(realpath "$bm/../jslib/html.sh")";
jslibSVG="$(realpath "$bm/../jslib/svg.sh")";
jslibJS="$(realpath "$bm/../jslib/lib.js/")";
tmpFile="$(mktemp)";

(
	cd "$data";
	cp -f "$jslibJS/"*.js "lib/";
	head -n5 index.html | tr -d '\n	';
	echo -n "<script type=\"module\">";
	jslib -i "$(grep "<script" index.html | grep -v "lib/load.js" | sed -e 's/.*src="\([^"]*\)".*/\1/')" | $jslibHTML "lib/" | $jslibSVG "lib/" | terser -cm | tr -d '\n'; # --mangle-props <- TODO:test this
	echo -n "</script><style type=\"text/css\">";
	grep -hv "^@import" *.css | uglifycss | tr -d '\n';
	echo -n "</style>";
	tail -n5 index.html | tr -d '\n	';
) > "$tmpFile";

echo -e "package battlemap\n\nconst (\n	uncompressedSize = $(stat --format "%s" "$tmpFile")\n	indexUpdated     = $(date "+%s")\n)" > "index_size.go";

zopfli --gzip --i1000 -c "$tmpFile" > index.gz;
rm -f "$tmpFile";
